name: Dockerhub
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
  - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build 7.4
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: olkitu/docker-laravel-project-template:7.4,olkitu/docker-laravel-project-template:7
        file: Dockerfile.7.4.image

    - name: Build 8.0
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: olkitu/docker-laravel-project-template:8.0,olkitu/docker-laravel-project-template:8,olkitu/docker-laravel-project-template:latest
        file: Dockerfile.8.0.image